apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7fhg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7fhg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7fhg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7fhg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7fhg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-krfp-tenant/rhtap-demo-app/hacbs-test-project-7fhg@sha256:a2484301eb41d0f2d5c0625b322330ffe82c49581d63c3c6b6fd65c258904622
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
